services:
  nginx:
    image: nginx:1.15-alpine
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/api/static
      - /etc/nginx/ssl/:/etc/nginx/ssl/
    networks:
      - dis-net
  app:
    build: ./api
    restart: unless-stopped
    volumes:
        - ./api:/api
        - static_volume:/api/static
    environment:
      - PYTHONUNBUFFERED=1
      - CONFIG_SERVER_URL=https://config.int.janelia.org/
    networks:
        - dis-net

networks:
  dis-net:
      driver: bridge

volumes:
  static_volume:
